#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/event-subscriber .
docker build -t ${REPO}/event-subscriber:${TAG} .

echo Built ${REPO}/event-subscriber:${TAG}
